apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-getting-started.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "docker-getting-started.name" . }}
