trigger:
  - main

pool:
  name: wsl-agent

variables:
  dockerRegistryServiceConnection: 'DockerHubServiceConnection'
  imageRepository: 'jhonbilly/docker-getting-started'
  containerRegistry: '$dockerRegistryServiceConnection'
  tag: '$(Build.BuildId)'
  SONAR_HOST_URL: 'http://172.20.38.158:9000'
  SONAR_PROJECT_KEY: 'docker-getting-started'
  SONAR_TOKEN: 'f4926fec98e5dd8491fd55400c0c167711d23aa2'

stages:
  - stage: AnalyzeAndBuild
    jobs:
      # 1. SonarQube Analysis (con continueOnError)
      - job: SonarQubeAnalysis
        displayName: 'SonarQube Analysis'
        continueOnError: true
        steps:
          - script: |
              cd node/
              npm install
            displayName: 'NPM Install'
          - script: |
              export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
              export PATH=$JAVA_HOME/bin:$PATH
              cd node/sample
              sonar-scanner \
                -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
                -Dsonar.sources=. \
                -Dsonar.host.url=$(SONAR_HOST_URL) \
                -Dsonar.login=$(SONAR_TOKEN)
            displayName: 'Run SonarQube Scanner'

      # 2. Build Job: SOLO si SonarQubeAnalysis fue OK
      - job: BuildApp
        displayName: 'Build app (solo si SonarQube OK)'
        dependsOn: SonarQubeAnalysis
        condition: succeeded('SonarQubeAnalysis')
        steps:
          - script: |
              echo "Análisis SonarQube exitoso, compilando app..."
              cd node/sample
              npm run build
            displayName: 'NPM Build'

      # 3. Escenario Fallido: SOLO si SonarQubeAnalysis Falla
      - job: SonarQubeFailed
        displayName: 'SonarQube Fallido'
        dependsOn: SonarQubeAnalysis
        condition: failed('SonarQubeAnalysis')
        steps:
          - script: |
              echo "El análisis SonarQube FALLÓ. Revisar calidad de código antes de continuar."
              exit 1
            displayName: 'Mensaje Fallo SonarQube'

  # (Las demás stages igual que antes: DockerBuildPush, DeployK8s)
  - stage: DockerBuildPush
    dependsOn: AnalyzeAndBuild
    jobs:
      - job: DockerImage
        steps:
          - task: Docker@2
            displayName: Login to registry
            inputs:
              command: login
              containerRegistry: 'DockerHubServiceConnection'
          - task: Docker@2
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'buildAndPush'
              Dockerfile: '**/node/sample/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/node'
              tags: '$(Build.BuildId)'

  - stage: DeployK8s
    dependsOn: DockerBuildPush
    jobs:
      - deployment: DeployApp
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmInstaller@1
                  inputs:
                    helmVersionToInstall: 'latest'
                - task: HelmDeploy@0
                  inputs:
                    connectionType: Kubernetes Service Connection
                    kubernetesServiceEndpoint: 'aks-demo-service-connection' 
                    command: 'upgrade'
                    chartType: 'FilePath'
                    chartPath: '$(Build.SourcesDirectory)/helm/docker-getting-started'
                    releaseName: 'getting-started'
                    overrideValues: |
                      image.repository=$(containerRegistry)/$(imageRepository)
                      image.tag=$(tag)
                    install: true
                    arguments: '--wait --timeout 900s --atomic'
