trigger: none  # Manual or artifact-trigger

pool:
  name: wsl-agent

resources:
  pipelines:
    - pipeline: buildPipeline
      source: jhonbilly.docker-init-demos
      trigger: true

stages:
  - stage: DeployK8s
    jobs:
      - deployment: DeployApp
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: buildPipeline
                  artifact: imagetag
                - script: |
                    export TAG=$(cat $(Pipeline.Workspace)/buildPipeline/imagetag/image-tag.txt)
                    echo "##vso[task.setvariable variable=imageTag]$TAG"
                  displayName: 'Parse image tag'
                - task: HelmInstaller@1
                  inputs:
                    helmVersionToInstall: 'latest'
                - task: HelmDeploy@0
                  inputs:
                    connectionType: Kubernetes Service Connection
                    kubernetesServiceEndpoint: 'aks-demo-service-connection' 
                    command: 'upgrade'
                    chartType: 'FilePath'
                    chartPath: '$(Build.SourcesDirectory)/helm/docker-getting-started'
                    releaseName: 'getting-started'
                    overrideValues: |
                      image.repository=jhonbilly/docker-getting-started
                      image.tag=$(imageTag)
                    install: true
                    arguments: '--wait --timeout 900s --atomic'
